DATASET:
  DATA_ROOT: /home/disk/data/ANNS
  DATA_NAME: Deep1M
  MEAN: 19.1029
  SIGMA: 1.3511

STRUC:
  MODEL: 'CCST'
  FEAT_DIM: 256
  EXPAND: 4
  TOKEN_NUM: 8
  DEPTH: [1, 1]
  HEADS: [4, 4]
  ATTN_RATIO: 4
  MLP_RATIO: 1
  C_FACTOR: 2

DATALOADER:
  NUM_WORKERS: 4
  BATCH_SIZE_TRAIN: 1024
  BATCH_SIZE_TEST: 1024

SOLVER:
  INIT_LR: 1e-4
  OPTIM: adamw
  VISUAL: True
  MAX_EPOCH: 2400
  LOSS: 'CR_loss_l2_s_log1'

OUTPUT_DIR: output